version: '3.8'

# --- RÉSEAUX ---
networks:
  app_net:
    driver: bridge # Correction : Utilisation du driver 'bridge' compatible rootless

# --- VOLUMES ---
volumes:
  db_data:
  logs:

# --- SERVICES (Conteneurs) ---
services:
  db:
    image: docker.io/library/postgres:16-alpine # Correction : Nom d'image complet
    container_name: votingapp_db
    restart: always # Stratégie de redémarrage simple
    networks:
      - app_net
    volumes:
      - db_data:/var/lib/postgresql/data:Z # Correction : Ajout de :Z pour rootless
    environment:
      POSTGRES_USER: rostam
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting_db

  api:
    image: localhost/votingapp-api:latest # Utilise l'image construite en MISSION 3
    container_name: votingapp_api
    restart: always
    networks:
      - app_net
    volumes:
      - logs:/app/logs:Z # Correction : Ajout de :Z pour rootless
    environment:
      DB_HOST: db
      DB_NAME: voting_db
      DB_USER: rostam
      DB_PASSWORD: password
    depends_on:
      - db # Démarre après la base de données

  reverse:
    image: docker.io/library/nginx:alpine # Correction : Nom d'image complet
    container_name: votingapp_reverse
    restart: always
    networks:
      - app_net
    ports:
      - "5000:80" # Correction : Port non privilégié (5000) pour l'hôte
    volumes:
      # Chemin absolu nécessaire pour le mode rootless et :Z pour les permissions
      - /home/rostam/tp_docker/reverse/nginx.conf:/etc/nginx/conf.d/default.conf:Z
    depends_on:
      - api # Démarre après l'API

  monitor:
    image: docker.io/library/alpine:latest # Correction : Nom d'image complet
    container_name: votingapp_monitor
    command: sleep 3600 # Garde le conteneur Alpine en vie
    restart: always
    networks:
      - app_net
      - app_net
    ports:
      - "80:80" # Port d'entrée principal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  monitor:
    image: votingapp-monitor:latest
    build: ./monitor
    networks:
      - app_net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == worker # Exemple pour le Worker2
